### ISSUE TITLE
Module oddball exp: no markers saved

### ISSUE THREAD

**Issue by BenGodde** [kylemath/EEGEdu#117]
**Describe the bug**
The saved csv file does not contain any marker (stimulus or response). Tried on Windows tablet and Android Smartphone

**To Reproduce**
1. Go to 'ERP experiment'
2. Start exp
3. Touch on red circles
4. Close window after csv is saved

**Desktop (please complete the following information):**
 - OS: Win 10 
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Device: [Huawei P10 lite]
 - OS: [Android 8]
 - Browser [chrome]

**Comment by BenGodde** [comment]
Solved

**Comment by kylemath** [comment]
what was the solution @BenGodde

**Comment by BenGodde** [comment]
It was my fault. Overlooked the (very) sparse markers. Only when plotting it I realized it.
