### ISSUE TITLE
Double the Delta Waves

### ISSUE THREAD

**Issue by MCalaresu** [kylemath/EEGEdu#140]
Hi Kyle,

Dumb question time! So I've been going over our power results from the MUSE readings we took last class (eye closed/opened). Anyway, when I was going over the raw data, I noticed there were actually two sets of delta readings in the file, one at the very beginning and one at the very end. They are present in all four of our individual reading sets and are markedly different from one another (delta beginning vs. delta end). Did I miss something?

Cheers, Mike

**Comment by kylemath** [comment]
fixed in https://github.com/kylemath/EEGEdu/pull/141
