### ISSUE TITLE
Are there eeg datasets that lend themselves to strong classification results?

### ISSUE THREAD

**Issue by CraigAlanFriedman** [kylemath/EEGEdu#149]
I've run the Muse notebook https://colab.research.google.com/github/kylemath/DeepEEG/blob/master/notebooks/Deep_EEG_Muse.ipynb#scrollTo=3HiHs8CluhjP, tried different model_types and set frequency_domain to True, but haven't seen model accuracy better than .5.

**Comment by kylemath** [comment]
please create this issue in the deepeeg repo
